"""
Narrative Twist (NT) — scoring engine.
================================================================================

Measures how much a target sentence S2 is a genuine *narrative twist* inside a
story S1 -> S2 -> S3 (method agreed with Itzik Fradkin / Anna Gorbunov).

Intuition
---------
S2 is a twist if it makes the real continuation S3 far more likely than a
*banal* sentence would. We compare:
  - the real world:  P(S3 | S1, S2)                              (the "posterior")
  - a banal world :  Q = mean_i P(S3 | S1, S2*_i)                (the "prior")
where S2*_i are banal alternative sentences generated by the model from S1.

Score
-----
    nt = log( P(S3 | S1, S2) / Q )          (a log-ratio; nt > 0  =>  twist)

All probabilities are computed **per token** (geometric mean, perplexity-style)
so that sentences of different lengths are comparable — see
`log_prob_of_continuation`.

Design
------
The score (`narrative_twist`) is backend-agnostic. A "backend" is any object
exposing two primitives:
    backend.log_prob_of_continuation(context, continuation) -> (sum_log_prob, n_tokens)
    backend.generate_alternatives(s1, n, temperature=..., seed=...) -> list[str]
Two backends are provided:
    - HFBackend       : transformers / distilgpt2  (fast, English, for development)
    - LlamaCppBackend : Hebrew-Mistral-7B GGUF      (the model used for the study)

CLI (quick self-test on the ghost example)
------------------------------------------
    python narrative_twist.py --backend hf                    # English demo
    python narrative_twist.py --backend llamacpp --lang he    # Hebrew demo (7B)

For batch scoring of a whole dataset, use `run_texts.py`.
"""

import argparse
import math
from typing import List, Optional, Tuple


# ===========================================================================
# Backends
# ===========================================================================
class HFBackend:
    """HuggingFace transformers backend (default: distilgpt2).

    Small and fast — meant for development/plumbing. It tokenizes non-English
    text poorly, so scores on the Hebrew data are only meaningful with the
    LlamaCppBackend below.
    """

    def __init__(self, model_name: str = "distilgpt2"):
        # Imported lazily so the module can be used with only one backend's deps.
        import torch
        from transformers import AutoTokenizer, AutoModelForCausalLM
        self.torch = torch
        print(f"Loading {model_name} (transformers)...")
        self.tokenizer = AutoTokenizer.from_pretrained(model_name)
        self.model = AutoModelForCausalLM.from_pretrained(model_name)
        self.model.eval()                       # inference mode (no gradients)
        print("Model ready.\n")

    def log_prob_of_continuation(self, context: str, continuation: str) -> Tuple[float, int]:
        """Return (sum of log P over the continuation tokens, n_continuation_tokens).

        A causal LM only ever predicts the *next* token: at position i its output
        distribution is over token i+1. So P(continuation | context) is built
        token by token and multiplied (i.e. log-probs are summed):

          1. tokenize the context alone -> its length `ctx_len`;
          2. tokenize "context + ' ' + continuation" -> the full sequence;
          3. one forward pass -> logits of shape (seq_len, vocab);
          4. log-softmax -> per-position log-probabilities;
          5. the continuation tokens sit at positions [ctx_len .. seq_len-1];
             each is *predicted* by the previous position, so we read their
             log-probs from logit rows [ctx_len-1 .. seq_len-2];
          6. sum those log-probs.

        The token count is returned so the caller can length-normalize
        (divide by n) to get a per-token, length-independent quantity.
        """
        import torch.nn.functional as F
        torch = self.torch

        ctx_ids = self.tokenizer(context, return_tensors="pt").input_ids.to(self.model.device)
        full_ids = self.tokenizer(context + " " + continuation,
                                  return_tensors="pt").input_ids.to(self.model.device)
        ctx_len = ctx_ids.shape[1]
        if full_ids.shape[1] <= ctx_len:        # continuation added no new tokens
            return 0.0, 0

        with torch.no_grad():
            logits = self.model(full_ids).logits          # (1, seq_len, vocab)
        log_probs = F.log_softmax(logits[0], dim=-1)      # (seq_len, vocab)

        target_ids = full_ids[0, ctx_len:]                # the continuation tokens
        pred_logprobs = log_probs[ctx_len - 1: -1, :]     # rows that predict them
        token_logprobs = pred_logprobs.gather(1, target_ids.unsqueeze(-1)).squeeze(-1)
        return token_logprobs.sum().item(), token_logprobs.shape[0]

    def generate_alternatives(self, s1: str, n_alternatives: int, max_new_tokens: int = 20,
                              temperature: float = 1.0, top_k: int = 50,
                              seed: Optional[int] = None) -> List[str]:
        """Generate up to `n_alternatives` banal sentences that could follow S1.

        Sampling (not greedy) so the alternatives vary; we keep only the first
        sentence of each generation. May return fewer than `n_alternatives` if
        some generations are empty.
        """
        torch = self.torch
        if seed is not None:
            torch.manual_seed(seed)             # reproducible sampling
        inputs = self.tokenizer(s1, return_tensors="pt").to(self.model.device)
        prompt_len = inputs.input_ids.shape[1]
        with torch.no_grad():
            outputs = self.model.generate(
                **inputs, max_new_tokens=max_new_tokens, do_sample=True,
                temperature=temperature, top_k=top_k,
                num_return_sequences=n_alternatives,
                pad_token_id=self.tokenizer.eos_token_id,
            )
        alternatives = []
        for out in outputs:
            text = self.tokenizer.decode(out[prompt_len:], skip_special_tokens=True).strip()
            first = text.split(".")[0].strip()  # keep only the first sentence
            if first:
                alternatives.append(first + ".")
        return alternatives


class LlamaCppBackend:
    """llama-cpp-python backend for Hebrew-Mistral-7B (GGUF, Q4_K_M).

    This is the model used for the study. Runs on the Apple GPU via Metal.
    """

    def __init__(self, model_path: str = "models/Hebrew-Mistral-7B.Q4_K_M.gguf",
                 n_ctx: int = 2048):
        import os
        from llama_cpp import Llama            # lazy import (heavy dependency)
        if not os.path.exists(model_path):
            raise SystemExit(f"Model file not found: {model_path}")
        print(f"Loading {model_path} (llama.cpp, Metal GPU)...")
        # logits_all=True is required to read the per-token logits we need for
        # log_prob_of_continuation; n_gpu_layers=-1 offloads all layers to the GPU.
        self.llm = Llama(model_path=model_path, n_ctx=n_ctx, n_gpu_layers=-1,
                         logits_all=True, verbose=False)
        print("Model ready.\n")

    def log_prob_of_continuation(self, context: str, continuation: str) -> Tuple[float, int]:
        """Same contract as HFBackend.log_prob_of_continuation, via llama.cpp.

        llama.cpp exposes the logits per position after `eval`; we apply a stable
        log-softmax by hand (subtract the max before exp) to avoid overflow.
        """
        llm = self.llm
        # Tokenize on raw UTF-8 bytes (GGUF works at the byte level); add_bos adds
        # the beginning-of-sequence token, consistently for context and full text.
        ctx_tokens = llm.tokenize(context.encode("utf-8"), add_bos=True)
        full_tokens = llm.tokenize((context + " " + continuation).encode("utf-8"), add_bos=True)
        ctx_len = len(ctx_tokens)
        cont_tokens = full_tokens[ctx_len:]     # continuation tokens only
        if not cont_tokens:
            return 0.0, 0

        llm.reset()
        llm.eval(full_tokens)
        logits_all = llm.eval_logits            # logits_all[i] predicts token i+1

        total_logp = 0.0
        for j, tok_id in enumerate(cont_tokens):
            logits = logits_all[ctx_len - 1 + j]        # row that predicts this token
            max_l = max(logits)                          # stable log-softmax
            log_sum_exp = max_l + math.log(sum(math.exp(l - max_l) for l in logits))
            total_logp += logits[tok_id] - log_sum_exp
        return total_logp, len(cont_tokens)

    def generate_alternatives(self, s1: str, n_alternatives: int, max_new_tokens: int = 30,
                              temperature: float = 1.0, top_k: int = 50,
                              seed: Optional[int] = None) -> List[str]:
        """Generate up to `n_alternatives` banal continuations of S1 (one per call).

        A distinct seed per alternative (seed + i) keeps the whole run
        reproducible while still producing different sentences.
        """
        prompt = s1 + " "
        alternatives = []
        for i in range(n_alternatives):
            out = self.llm(prompt, max_tokens=max_new_tokens, temperature=temperature,
                           top_k=top_k, seed=(seed + i) if seed is not None else -1,
                           echo=False)
            text = out["choices"][0]["text"].strip()
            for sep in (".", "?", "!"):         # keep only the first sentence
                if sep in text:
                    text = text.split(sep)[0] + sep
                    break
            if text:
                alternatives.append(text)
        return alternatives


def make_backend(kind: str, model: Optional[str] = None):
    """Factory: 'hf' -> HFBackend, 'llamacpp' -> LlamaCppBackend."""
    if kind == "hf":
        return HFBackend(model or "distilgpt2")
    if kind == "llamacpp":
        return LlamaCppBackend(model or "models/Hebrew-Mistral-7B.Q4_K_M.gguf")
    raise ValueError(f"Unknown backend {kind!r} (expected 'hf' or 'llamacpp').")


# ===========================================================================
# NT score (backend-agnostic)
# ===========================================================================
def narrative_twist(s1: str, s2: str, s3: str, backend, n_alternatives: int = 10,
                    seed: int = 42, verbose: bool = False,
                    alternatives: Optional[List[str]] = None) -> Optional[dict]:
    """Compute the NT score of sentence S2 given context S1 and continuation S3.

    If `alternatives` (a list of S2*) is provided it is reused instead of being
    regenerated — useful to share the same S2* across several definitions of S3
    (e.g. the 'next' and 'all' modes) on the same sentence without paying twice
    for generation.

    Returns a dict of the score and its ingredients, or None if the prior could
    not be estimated (no usable alternative).
    """
    # --- 1) Posterior: the real world. Length-normalized (per token). ---
    logp_post, n_post = backend.log_prob_of_continuation(s1 + " " + s2, s3)
    if n_post == 0:
        return None
    log_post = logp_post / n_post

    # --- 2) Banal alternatives S2*_i (generated only if not supplied). ---
    if alternatives is None:
        alternatives = backend.generate_alternatives(s1, n_alternatives, seed=seed)

    # --- 3) Priors: one per alternative (keep the per-alternative detail too). ---
    priors_per_tok = []                         # per-token log P(S3 | S1, S2*_i)
    prior_details = []                          # [(S2* text, that log-prob)]
    for s2_alt in alternatives:
        lp, n = backend.log_prob_of_continuation(s1 + " " + s2_alt, s3)
        if n > 0:
            priors_per_tok.append(lp / n)
            prior_details.append((s2_alt, lp / n))
    if not priors_per_tok:                      # every alternative failed
        return None

    # --- 4) Average the priors IN PROBABILITY SPACE (as the formula requires).
    # Q = mean_i P(...). We exponentiate each per-token log-prob, average, then
    # take the log. Averaging the log-probs directly would give the geometric
    # mean instead of the arithmetic mean — a different (wrong) quantity.
    mean_prior = sum(math.exp(lp) for lp in priors_per_tok) / len(priors_per_tok)
    log_prior = math.log(mean_prior)

    # --- 5) Score = log-ratio of posterior to prior. ---
    nt = log_post - log_prior                   # = log( P(S3|S1,S2) / Q )
    ratio = math.exp(nt)                        # same thing on the linear scale

    if verbose:
        print(f"  S1: {s1}")
        print(f"  S2: {s2}")
        print(f"  S3: {s3}")
        print(f"  log P(S3|S1,S2)       = {log_post:.3f}  (per token)")
        print(f"  log mean P(S3|S1,S2*) = {log_prior:.3f}  (per token)")
        print(f"  nt = log(P/Q)         = {nt:.4f}   (ratio {ratio:.2f}x, "
              f"{len(prior_details)} alternatives)")

    return {
        "nt": nt,                               # the score
        "log_post": log_post,
        "log_prior": log_prior,
        "ratio": ratio,
        "alternatives": alternatives,
        "prior_details": prior_details,         # [(S2* text, its per-token log-prob)]
    }


# ===========================================================================
# CLI — quick self-test on the ghost example (twist vs. banal)
# ===========================================================================
EXAMPLES = {
    "en": {
        "s1": "David lay down on his bed.",
        "twist": ("Suddenly, a ghost came.", "The ghost scared David."),
        "banal": ("He closed his eyes.", "He fell asleep."),
    },
    "he": {
        "s1": "דוד שכב על המיטה שלו.",
        "twist": ("לפתע, רוח רפאים הגיעה.", "רוח הרפאים הפחידה את דוד."),
        "banal": ("הוא עצם את העיניים.", "הוא נרדם."),
    },
}


def main():
    ap = argparse.ArgumentParser(description="Narrative Twist (NT) — quick demo.")
    ap.add_argument("--backend", choices=["hf", "llamacpp"], default="hf")
    ap.add_argument("--lang", choices=["en", "he"], default=None,
                    help="Demo language (default: en for hf, he for llamacpp).")
    ap.add_argument("--model", default=None, help="HF model name or GGUF path.")
    ap.add_argument("--n-alternatives", type=int, default=10)
    ap.add_argument("--seed", type=int, default=42)
    args = ap.parse_args()

    lang = args.lang or ("he" if args.backend == "llamacpp" else "en")
    ex = EXAMPLES[lang]
    backend = make_backend(args.backend, args.model)
    s2_twist, s3_twist = ex["twist"]
    s2_banal, s3_banal = ex["banal"]

    print("=" * 70 + f"\nCASE 1 — story WITH a twist [{lang}]\n" + "=" * 70)
    r1 = narrative_twist(ex["s1"], s2_twist, s3_twist, backend,
                         n_alternatives=args.n_alternatives, seed=args.seed, verbose=True)
    print("\n" + "=" * 70 + f"\nCASE 2 — story WITHOUT a twist [{lang}]\n" + "=" * 70)
    r2 = narrative_twist(ex["s1"], s2_banal, s3_banal, backend,
                         n_alternatives=args.n_alternatives, seed=args.seed, verbose=True)

    print("\n" + "=" * 70 + "\nRESULT — does NT rank the twist above the banal case?\n" + "=" * 70)
    print(f"  nt(twist) = {r1['nt']:.4f}")
    print(f"  nt(banal) = {r2['nt']:.4f}")
    print(f"  -> {'OK: twist > banal' if r1['nt'] > r2['nt'] else 'NO: twist <= banal'}")


if __name__ == "__main__":
    main()
